### ISSUE TITLE
[FR] Issue with using space at the end of custom searchs

### ISSUE THREAD

**Issue by Archie-2021** [tadashi-aikawa/obsidian-another-quick-switcher#175]
Hello

I have an issue using custom search, I create a lot of custom search for notes with different tags and I assign hotkeys to make my search quicker but when AQS starts with stated tags it do not consider the spaces at the end so I have to either enter a space again manually and then start to insert my search key or it is going to search for a wrong search tag with zero results.

Thanks for this great plugin

**Comment by tadashi-aikawa** [comment]
Hi, @Archie-2021 :)

Please insert a white space after the tag in the "Default input" setting.

![image](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/assets/9500018/00f2bbac-6627-484a-90d6-65d556f9c16b)

**Comment by Archie-2021** [comment]
> Hi, @Archie-2021 :)
> 
> Please insert a white space after the tag in the "Default input" setting.
> 
> ![image](https://user-images.githubusercontent.com/9500018/239665131-00f2bbac-6627-484a-90d6-65d556f9c16b.png)

I have tried that before multiple times. Maybe it got fixed in a recent update. I will test it again and let you know.

**Comment by tadashi-aikawa** [comment]
I’m glad to hear that!

That's so weird. I didn't fix it, nor did I make any related updates... 🤔

**Comment by Archie-2021** [comment]
> I’m glad to hear that!
> 
> That's so weird. I didn't fix it, nor did I make any related updates... thinking

Interesting , it was probably a side effect that has been changed on a update.
